# main.yml
---
- name: Great_scenario
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  vars:
#centos_server
   - ip_rsyslog_server: 10.6.1.33
#debian_rsyslog_server
   - ip_rsyslog_server: 10.6.194.112

  tasks:

# 1 проверка ос
#   - include: ./tasks/check_os_task.yml

# 2 установка моих пакетов для дебага ( nano \ tcpdump \ nc \ и т.д.)
#   - include: ./tasks/add_my_package.yml

# 3 проверка версии rsyslog для серверов на CentOS параметр rsyslog_installed - значить установлен
   - include: ./tasks/check_rsyslog_rpm_task.yml
     when: ansible_distribution == "CentOS"

# 4 проверка что rsyslog запущен для CentOS
   - include: ./tasks/check_rsyslog_systemctl_task.yml
     when: ansible_distribution == "CentOS"

# 5 проверка что config rsyslog нормальный и рабочий
   - include: ./tasks/check_rsyslog_config.yml
     when: ansible_distribution == "CentOS" and (rsyslog_status.rc == 0)

# 6 проверка что SeLinux запущен в Enforce
#   - include: ./tasks/check_status_selinux.yml
#     when: ansible_distribution == "CentOS"

# 7 проверка версии auditd
   - include: ./tasks/check_audit_rpm_task.yml
     when: ansible_distribution == "CentOS"

# 8 установка rsyslog нашей версии если его нет
   - include: ./tasks/install_rsyslog_task.yml
     when: ansible_distribution == "CentOS" and ("not 'rsyslog' in rsyslog_rpm.stdout" or "not 'rsyslog-relp' in rsyslog-relp_rpm.stdout" or "not 'rsyslog-gnutls' in rsyslog-gnutls_rpm.stdout")

# 9 copy_certs
   - include: ./tasks/copy_certs.yml
#     when: ansible_distribution == "CentOS" and ("not 'rsyslog' in rsyslog_rpm.stdout" or "not 'rsyslog-relp' in rsyslog-relp_rpm.stdout" or "not 'rsysl$

# 10 проверка что config rsyslog нормальный и рабочий - после установки
   - include: ./tasks/check_rsyslog_config.yml
     when: ansible_distribution == "CentOS"

# 11 копирование конфигов rsyslog (и restart) если есть ошибки в конфиге rsysloga (если рсислог был не установлен\если был не запущен)
   - include: ./tasks/copy_rsyslog_config.yml
     when: ansible_distribution == "CentOS"

#     when: "'error during parsing file' in rsyslog_config_status.stderr"


#12 доставка audiSP
   - include: ./tasks/install_audiSP_task.yml
     when: ansible_distribution == "CentOS"

# 13 доставка правил аудит-д
   - include: ./tasks/install_auditd_task.yml
     when: ansible_distribution == "CentOS"

# 14 проверка что auditd -иммутэйбил (имеет в конце конфига правил строку -e 2)
   - include: ./tasks/check_auditd_rules.yml
     when: ansible_distribution == "CentOS"

# 15 инфа что нужно заребутить сервер
   - name: Please restart server for accept auditd.rules
     check_mode: no
     failed_when: false
     changed_when: false
     debug:
       msg: "****Please restart server for accept auditd.rules (-e 2)****** {{ansible_hostname}} ip {{inventory_hostname}}"
     when: auditd_e_status == 0
