---
#сбор инф. и проверка что пакет rsyslog есть
- name: Part1 Check ver rsyslog sbor with rpm -qa grep rsyslog
  shell: rpm -qa | grep rsyslog
  check_mode: no
  failed_when: false
  changed_when: false
  register: rsyslog_rpm


- name: Check ver rsyslog-relp
  shell: rpm -qa | grep rsyslog-relp
  check_mode: no
  failed_when: false
  changed_when: false
  register: rsyslog-relp_rpm

- name: Check ver rsyslog-gnutls
  shell: rpm -qa | grep rsyslog-gnutls
  check_mode: no
  failed_when: false
  changed_when: false
  register: rsyslog-gnutls_rpm


#вывод что пакет установлен
- name: Check ver rsyslog sbor with rpm -qa grep rsyslog
  debug: msg="RSYSLOG is INSTALLED on the {{ansible_hostname}}"
  when: ("'rsyslog' in rsyslog_rpm.stdout") and ("'rsyslog-relp' in rsyslog-relp_rpm.stdout")

#вывод что пакета нет
- name: Check ver rsyslog sbor with rpm -qa grep rsyslog2
  debug: msg="Rsyslog-relp is NOOOT! installed on the remote host"
  when: not 'rsyslog' in rsyslog_rpm.stdout

