# main.yml
---
- name: Great_scenario
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  vars:
#Minsk_centos_server
#   - ip_rsyslog_server: 10.6.1.33
#Kyiv_rsyslog_server
   - ip_rsyslog_server: 10.17.14.76

  tasks:

# 1 проверка ос
   - include: ./tasks/check_os_task.yml

# 2 установка моих пакетов для дебага ( nano \ tcpdump \ nc \ и т.д.)
#   - include: ./tasks/add_my_package.yml

# 3 установка rsyslog нашей версии если его нет
   - include: ./tasks/install_rsyslog_task_ubuntu.yml
     when: ansible_distribution == "Debian" 

# 4 copy_certs
   - include: ./tasks/copy_certs.yml
#     when: ansible_distribution == "CentOS" and ("not 'rsyslog' in rsyslog_rpm.stdout" or "not 'rsyslog-relp' in rsyslog-relp_rpm.stdout" or "not 'rsysl$

# 5 копирование конфигов rsyslog (и restart) если есть ошибки в конфиге rsysloga (если рсислог был не установлен\если был не запущен)
   - include: ./tasks/copy_rsyslog_config.yml
     when: ansible_distribution == "Debian"


# 6 доставка audiSP
   - include: ./tasks/install_audiSP_task_debian.yml
     when: ansible_distribution == "Debian"

# 7 доставка правил аудит-д
   - include: ./tasks/install_auditd_task.yml
     when: ansible_distribution == "Debian"

